# Generated by Django 5.0.2 on 2024-06-20 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footgram', '0002_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='user_name',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
